### ISSUE TITLE
#你好

### ISSUE THREAD

**Issue by kaifangjilu** [xgit01/sgkrank#1]
你好 可以留你的联系方式吗 我有点问题请教你 有费用

**Comment by kaifangjilu** [comment]
看到信息可以回复么？

**Comment by sgkchaxun** [comment]
博主看到后请回复我

**Comment by xgit01** [comment]
> 你好 可以留你的联系方式吗 我有点问题请教你 有费用

这里只是分享、整理，不提供付费服务~

**Comment by sgkchaxun** [comment]
我这里想要跟您合作 老板 麻烦你联系一下我吧 TG kefu1

**Comment by sgkchaxun** [comment]
不然您这边的联系方式给我一个 我这边联系您可以吗

**Comment by sgkchaxun** [comment]
我这边是真心想跟您合作 希望您能够给我这个机会

**Comment by sgkchaxun** [comment]
我这边需要您请教您这个github上的一些问题 更希望您能跟我合作 我们这边不会少您钱的 真心想合作 我已经试着联系你很久了 迟迟都没有得到回复 抱歉 请您给我一个机会好吗？ 联系我的TG账号：kefu1 或者您的联系方式给我也可以的！
